DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS userPass;
DROP TABLE IF EXISTS presetPasses;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE userPass (
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    user_id INTEGER NOT NULL,
    bpName TEXT NOT NULL,
    currentXP INTEGER NOT NULL DEFAULT 0,
    totalXP INTEGER NOT NULL,
    endDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE presetPasses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    bpName TEXT NOT NULL,
    totalXP INTEGER NOT NULL,
    endDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);